### ISSUE TITLE
Upgrade to 64-bit

### ISSUE THREAD

**Issue by FokkeZB** [animecyc/TiDraggable#19]
@animecyc any plans to upgrade this modules to 64-bit?

**Comment by fbrcdx** [comment]
+1

**Comment by DFoxinator** [comment]
Someone nice enough to maintain it and make great additions/fixes did so here: https://github.com/viezel/TiDraggable

**Comment by xavierlacot** [comment]
I guess this can be closed, after a4426d2928e1d9077248c4cf425e97a141301e1a ?
