### ISSUE TITLE
Create new release

### ISSUE THREAD

**Issue by parnanzio** [animecyc/TiDraggable#27]
Hi, can you create a new release with the 64-bit support?
The latest release version is *2.0.3* (23/01/2014).

Thank you.

**Comment by parnanzio** [comment]
Sorry, found the compiled module only after.

**Comment by darkhorse2013** [comment]
Where was the module @parnanzio ? Can't find the new release?

**Comment by parnanzio** [comment]
Sorry @darkhorse2013 , I found the 2.0.4 zip somewhere I don't remember.
I tried to look for it, but cannot find anymore.

@animecyc said he is working on the 3.0.0 version, so.. stay connected ;)

**Comment by darkhorse2013** [comment]
Can you zip up the module in your modules folder and post it on here?

**Comment by parnanzio** [comment]
Cannot upload here, but here is a link: http://cl.ly/0g0L0O092i31/ti.draggable_2.0.4.zip

**Comment by darkhorse2013** [comment]
Thanks will check it out
